from classes_02 import AnimaisMarinhos

marinho1 = AnimaisMarinhos()
marinho2 = AnimaisMarinhos()
marinho3 = AnimaisMarinhos()
marinho4 = AnimaisMarinhos()
marinho5 = AnimaisMarinhos()
marinho6 = AnimaisMarinhos()
marinho7 = AnimaisMarinhos()
marinho8 = AnimaisMarinhos()
marinho9 = AnimaisMarinhos()
marinho10 = AnimaisMarinhos()
marinho11 = AnimaisMarinhos()
marinho12 = AnimaisMarinhos()
marinho13 = AnimaisMarinhos()
marinho14 = AnimaisMarinhos()
marinho15 = AnimaisMarinhos()
marinho16 = AnimaisMarinhos()
marinho17 = AnimaisMarinhos()
marinho18 = AnimaisMarinhos()
marinho19 = AnimaisMarinhos()
marinho20 = AnimaisMarinhos()